/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CambiarContrasenaRouteImport } from './routes/cambiar-contrasena'
import { Route as ConductorRouteImport } from './routes/conductor'
import { Route as IngresarRouteImport } from './routes/ingresar'
import { Route as PanelRouteImport } from './routes/panel'
import { Route as ConductorIndexRouteImport } from './routes/conductor/index'
import { Route as ConductorCuentaRouteImport } from './routes/conductor/cuenta'
import { Route as PanelIndexRouteImport } from './routes/panel/index'
import { Route as PanelConductoresRouteImport } from './routes/panel/conductores'
import { Route as PanelCuentaRouteImport } from './routes/panel/cuenta'
import { Route as PanelDestinosRouteImport } from './routes/panel/destinos'
import { Route as PanelProductosRouteImport } from './routes/panel/productos'
import { Route as PanelUsuariosRouteImport } from './routes/panel/usuarios'
import { Route as PanelVehiculosRouteImport } from './routes/panel/vehiculos'
import { Route as PanelZonasRouteImport } from './routes/panel/zonas'
import { Route as PanelDestinosImportarRouteImport } from './routes/panel/destinos_.importar'
import { Route as PanelRutasIndexRouteImport } from './routes/panel/rutas/index'
import { Route as PanelRutasRutaIdRouteImport } from './routes/panel/rutas/$rutaId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CambiarContrasenaRoute = CambiarContrasenaRouteImport.update({
  id: '/cambiar-contrasena',
  path: '/cambiar-contrasena',
  getParentRoute: () => rootRouteImport,
} as any)
const ConductorRoute = ConductorRouteImport.update({
  id: '/conductor',
  path: '/conductor',
  getParentRoute: () => rootRouteImport,
} as any)
const IngresarRoute = IngresarRouteImport.update({
  id: '/ingresar',
  path: '/ingresar',
  getParentRoute: () => rootRouteImport,
} as any)
const PanelRoute = PanelRouteImport.update({
  id: '/panel',
  path: '/panel',
  getParentRoute: () => rootRouteImport,
} as any)
const ConductorIndexRoute = ConductorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ConductorRoute,
} as any)
const ConductorCuentaRoute = ConductorCuentaRouteImport.update({
  id: '/cuenta',
  path: '/cuenta',
  getParentRoute: () => ConductorRoute,
} as any)
const PanelIndexRoute = PanelIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PanelRoute,
} as any)
const PanelConductoresRoute = PanelConductoresRouteImport.update({
  id: '/conductores',
  path: '/conductores',
  getParentRoute: () => PanelRoute,
} as any)
const PanelCuentaRoute = PanelCuentaRouteImport.update({
  id: '/cuenta',
  path: '/cuenta',
  getParentRoute: () => PanelRoute,
} as any)
const PanelDestinosRoute = PanelDestinosRouteImport.update({
  id: '/destinos',
  path: '/destinos',
  getParentRoute: () => PanelRoute,
} as any)
const PanelProductosRoute = PanelProductosRouteImport.update({
  id: '/productos',
  path: '/productos',
  getParentRoute: () => PanelRoute,
} as any)
const PanelUsuariosRoute = PanelUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => PanelRoute,
} as any)
const PanelVehiculosRoute = PanelVehiculosRouteImport.update({
  id: '/vehiculos',
  path: '/vehiculos',
  getParentRoute: () => PanelRoute,
} as any)
const PanelZonasRoute = PanelZonasRouteImport.update({
  id: '/zonas',
  path: '/zonas',
  getParentRoute: () => PanelRoute,
} as any)
const PanelDestinosImportarRoute = PanelDestinosImportarRouteImport.update({
  id: '/destinos_/importar',
  path: '/destinos/importar',
  getParentRoute: () => PanelRoute,
} as any)
const PanelRutasIndexRoute = PanelRutasIndexRouteImport.update({
  id: '/rutas/',
  path: '/rutas/',
  getParentRoute: () => PanelRoute,
} as any)
const PanelRutasRutaIdRoute = PanelRutasRutaIdRouteImport.update({
  id: '/rutas/$rutaId',
  path: '/rutas/$rutaId',
  getParentRoute: () => PanelRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cambiar-contrasena': typeof CambiarContrasenaRoute
  '/conductor': typeof ConductorRouteWithChildren
  '/ingresar': typeof IngresarRoute
  '/panel': typeof PanelRouteWithChildren
  '/conductor/cuenta': typeof ConductorCuentaRoute
  '/panel/conductores': typeof PanelConductoresRoute
  '/panel/cuenta': typeof PanelCuentaRoute
  '/panel/destinos': typeof PanelDestinosRoute
  '/panel/productos': typeof PanelProductosRoute
  '/panel/usuarios': typeof PanelUsuariosRoute
  '/panel/vehiculos': typeof PanelVehiculosRoute
  '/panel/zonas': typeof PanelZonasRoute
  '/conductor/': typeof ConductorIndexRoute
  '/panel/': typeof PanelIndexRoute
  '/panel/destinos/importar': typeof PanelDestinosImportarRoute
  '/panel/rutas/$rutaId': typeof PanelRutasRutaIdRoute
  '/panel/rutas/': typeof PanelRutasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cambiar-contrasena': typeof CambiarContrasenaRoute
  '/ingresar': typeof IngresarRoute
  '/conductor/cuenta': typeof ConductorCuentaRoute
  '/panel/conductores': typeof PanelConductoresRoute
  '/panel/cuenta': typeof PanelCuentaRoute
  '/panel/destinos': typeof PanelDestinosRoute
  '/panel/productos': typeof PanelProductosRoute
  '/panel/usuarios': typeof PanelUsuariosRoute
  '/panel/vehiculos': typeof PanelVehiculosRoute
  '/panel/zonas': typeof PanelZonasRoute
  '/conductor': typeof ConductorIndexRoute
  '/panel': typeof PanelIndexRoute
  '/panel/destinos/importar': typeof PanelDestinosImportarRoute
  '/panel/rutas/$rutaId': typeof PanelRutasRutaIdRoute
  '/panel/rutas': typeof PanelRutasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cambiar-contrasena': typeof CambiarContrasenaRoute
  '/conductor': typeof ConductorRouteWithChildren
  '/ingresar': typeof IngresarRoute
  '/panel': typeof PanelRouteWithChildren
  '/conductor/cuenta': typeof ConductorCuentaRoute
  '/panel/conductores': typeof PanelConductoresRoute
  '/panel/cuenta': typeof PanelCuentaRoute
  '/panel/destinos': typeof PanelDestinosRoute
  '/panel/productos': typeof PanelProductosRoute
  '/panel/usuarios': typeof PanelUsuariosRoute
  '/panel/vehiculos': typeof PanelVehiculosRoute
  '/panel/zonas': typeof PanelZonasRoute
  '/conductor/': typeof ConductorIndexRoute
  '/panel/': typeof PanelIndexRoute
  '/panel/destinos_/importar': typeof PanelDestinosImportarRoute
  '/panel/rutas/$rutaId': typeof PanelRutasRutaIdRoute
  '/panel/rutas/': typeof PanelRutasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cambiar-contrasena'
    | '/conductor'
    | '/ingresar'
    | '/panel'
    | '/conductor/cuenta'
    | '/panel/conductores'
    | '/panel/cuenta'
    | '/panel/destinos'
    | '/panel/productos'
    | '/panel/usuarios'
    | '/panel/vehiculos'
    | '/panel/zonas'
    | '/conductor/'
    | '/panel/'
    | '/panel/destinos/importar'
    | '/panel/rutas/$rutaId'
    | '/panel/rutas/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cambiar-contrasena'
    | '/ingresar'
    | '/conductor/cuenta'
    | '/panel/conductores'
    | '/panel/cuenta'
    | '/panel/destinos'
    | '/panel/productos'
    | '/panel/usuarios'
    | '/panel/vehiculos'
    | '/panel/zonas'
    | '/conductor'
    | '/panel'
    | '/panel/destinos/importar'
    | '/panel/rutas/$rutaId'
    | '/panel/rutas'
  id:
    | '__root__'
    | '/'
    | '/cambiar-contrasena'
    | '/conductor'
    | '/ingresar'
    | '/panel'
    | '/conductor/cuenta'
    | '/panel/conductores'
    | '/panel/cuenta'
    | '/panel/destinos'
    | '/panel/productos'
    | '/panel/usuarios'
    | '/panel/vehiculos'
    | '/panel/zonas'
    | '/conductor/'
    | '/panel/'
    | '/panel/destinos_/importar'
    | '/panel/rutas/$rutaId'
    | '/panel/rutas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CambiarContrasenaRoute: typeof CambiarContrasenaRoute
  ConductorRoute: typeof ConductorRouteWithChildren
  IngresarRoute: typeof IngresarRoute
  PanelRoute: typeof PanelRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cambiar-contrasena': {
      id: '/cambiar-contrasena'
      path: '/cambiar-contrasena'
      fullPath: '/cambiar-contrasena'
      preLoaderRoute: typeof CambiarContrasenaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conductor': {
      id: '/conductor'
      path: '/conductor'
      fullPath: '/conductor'
      preLoaderRoute: typeof ConductorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ingresar': {
      id: '/ingresar'
      path: '/ingresar'
      fullPath: '/ingresar'
      preLoaderRoute: typeof IngresarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panel': {
      id: '/panel'
      path: '/panel'
      fullPath: '/panel'
      preLoaderRoute: typeof PanelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conductor/': {
      id: '/conductor/'
      path: '/'
      fullPath: '/conductor/'
      preLoaderRoute: typeof ConductorIndexRouteImport
      parentRoute: typeof ConductorRoute
    }
    '/conductor/cuenta': {
      id: '/conductor/cuenta'
      path: '/cuenta'
      fullPath: '/conductor/cuenta'
      preLoaderRoute: typeof ConductorCuentaRouteImport
      parentRoute: typeof ConductorRoute
    }
    '/panel/': {
      id: '/panel/'
      path: '/'
      fullPath: '/panel/'
      preLoaderRoute: typeof PanelIndexRouteImport
      parentRoute: typeof PanelRoute
    }
    '/panel/conductores': {
      id: '/panel/conductores'
      path: '/conductores'
      fullPath: '/panel/conductores'
      preLoaderRoute: typeof PanelConductoresRouteImport
      parentRoute: typeof PanelRoute
    }
    '/panel/cuenta': {
      id: '/panel/cuenta'
      path: '/cuenta'
      fullPath: '/panel/cuenta'
      preLoaderRoute: typeof PanelCuentaRouteImport
      parentRoute: typeof PanelRoute
    }
    '/panel/destinos': {
      id: '/panel/destinos'
      path: '/destinos'
      fullPath: '/panel/destinos'
      preLoaderRoute: typeof PanelDestinosRouteImport
      parentRoute: typeof PanelRoute
    }
    '/panel/productos': {
      id: '/panel/productos'
      path: '/productos'
      fullPath: '/panel/productos'
      preLoaderRoute: typeof PanelProductosRouteImport
      parentRoute: typeof PanelRoute
    }
    '/panel/usuarios': {
      id: '/panel/usuarios'
      path: '/usuarios'
      fullPath: '/panel/usuarios'
      preLoaderRoute: typeof PanelUsuariosRouteImport
      parentRoute: typeof PanelRoute
    }
    '/panel/vehiculos': {
      id: '/panel/vehiculos'
      path: '/vehiculos'
      fullPath: '/panel/vehiculos'
      preLoaderRoute: typeof PanelVehiculosRouteImport
      parentRoute: typeof PanelRoute
    }
    '/panel/zonas': {
      id: '/panel/zonas'
      path: '/zonas'
      fullPath: '/panel/zonas'
      preLoaderRoute: typeof PanelZonasRouteImport
      parentRoute: typeof PanelRoute
    }
    '/panel/destinos_/importar': {
      id: '/panel/destinos_/importar'
      path: '/destinos/importar'
      fullPath: '/panel/destinos/importar'
      preLoaderRoute: typeof PanelDestinosImportarRouteImport
      parentRoute: typeof PanelRoute
    }
    '/panel/rutas/': {
      id: '/panel/rutas/'
      path: '/rutas'
      fullPath: '/panel/rutas/'
      preLoaderRoute: typeof PanelRutasIndexRouteImport
      parentRoute: typeof PanelRoute
    }
    '/panel/rutas/$rutaId': {
      id: '/panel/rutas/$rutaId'
      path: '/rutas/$rutaId'
      fullPath: '/panel/rutas/$rutaId'
      preLoaderRoute: typeof PanelRutasRutaIdRouteImport
      parentRoute: typeof PanelRoute
    }
  }
}

interface ConductorRouteChildren {
  ConductorCuentaRoute: typeof ConductorCuentaRoute
  ConductorIndexRoute: typeof ConductorIndexRoute
}

const ConductorRouteChildren: ConductorRouteChildren = {
  ConductorCuentaRoute: ConductorCuentaRoute,
  ConductorIndexRoute: ConductorIndexRoute,
}

const ConductorRouteWithChildren = ConductorRoute._addFileChildren(
  ConductorRouteChildren,
)

interface PanelRouteChildren {
  PanelConductoresRoute: typeof PanelConductoresRoute
  PanelCuentaRoute: typeof PanelCuentaRoute
  PanelDestinosRoute: typeof PanelDestinosRoute
  PanelProductosRoute: typeof PanelProductosRoute
  PanelUsuariosRoute: typeof PanelUsuariosRoute
  PanelVehiculosRoute: typeof PanelVehiculosRoute
  PanelZonasRoute: typeof PanelZonasRoute
  PanelIndexRoute: typeof PanelIndexRoute
  PanelDestinosImportarRoute: typeof PanelDestinosImportarRoute
  PanelRutasRutaIdRoute: typeof PanelRutasRutaIdRoute
  PanelRutasIndexRoute: typeof PanelRutasIndexRoute
}

const PanelRouteChildren: PanelRouteChildren = {
  PanelConductoresRoute: PanelConductoresRoute,
  PanelCuentaRoute: PanelCuentaRoute,
  PanelDestinosRoute: PanelDestinosRoute,
  PanelProductosRoute: PanelProductosRoute,
  PanelUsuariosRoute: PanelUsuariosRoute,
  PanelVehiculosRoute: PanelVehiculosRoute,
  PanelZonasRoute: PanelZonasRoute,
  PanelIndexRoute: PanelIndexRoute,
  PanelDestinosImportarRoute: PanelDestinosImportarRoute,
  PanelRutasRutaIdRoute: PanelRutasRutaIdRoute,
  PanelRutasIndexRoute: PanelRutasIndexRoute,
}

const PanelRouteWithChildren = PanelRoute._addFileChildren(PanelRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CambiarContrasenaRoute: CambiarContrasenaRoute,
  ConductorRoute: ConductorRouteWithChildren,
  IngresarRoute: IngresarRoute,
  PanelRoute: PanelRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
