cliArgs:
  geometry: true
  planmode: false
  threads: 2
  explore: 5
  limit: '1mb'
  logdir: '/conf'
  logsize: '100M'
  maxlocations: 1000
  maxvehicles: 200
  override: true
  path: ''
  port: 3000
  router: 'osrm'
  timeout: 300000
routingServers:
  osrm:
    car:
      host: 'osrm'
      port: '5000'
